[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.build]
cmds = [
  "cd computing-portal",
  "npm ci",
  "npm run build"
]

[start]
cmd = "cd computing-portal && npm start"

[build]
workDir = "computing-portal"

