[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd computing-portal && npm ci"]

[phases.build]
cmds = ["cd computing-portal && npm run build"]

[start]
cmd = "cd computing-portal && npm start"
